name: test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  intl_utils: ^2.4.0
  location: ^7.0.1
  flag: ^7.0.0
  image_picker: 0.8.7+3
  cached_network_image: ^3.2.3 # For efficient image caching

  #google_maps_flutter: ^2.0.9
  #google_maps_flutter: ^2.10.0
   # Add Google Maps Flutter package
  #image_picker: ^0.8.5+3  # Uncommented the image_picker version you want to use

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - images/Homie_logo.png
    - images/Teaching.jpg
    - images/plumper.jpg
    - images/Cleaning.jpg
    - images/electrion.jpg
    - lib/l10n/  # For localization files

  generate: true  # Enable code generation (for localization files)
